/**
 * Generated test code for RBMC stations. Bump RBMC_TEMPLATE_VERSION whenever
 * the body changes — the sync rewrites every linked test whose stored version
 * (or actual code) differs, so the change rolls out without manual edits.
 */

export const RBMC_TEMPLATE_VERSION = 1

export const RBMC_TAG = 'rbmc'

/** Mirrors the hand-made tests the RBMC instance was created with. */
export const RBMC_TEST_DEFAULTS = Object.freeze({
  schedule_ms: 900_000,
  timeout_ms: 10_000,
  retries: 1,
  uses_browser: false,
  failure_threshold: 3,
  cooldown_ms: 86_400_000,
  tags: [RBMC_TAG] as string[],
})

const CODE_RE = /^[A-Z0-9]{4}$/

export function buildStationTestName(code: string, city: string | null): string {
  const label = city && city.trim() !== '' ? city.trim() : code
  return `RBMC - ${code} - ${label}`
}

export function buildStationTestCode(code: string): string {
  if (!CODE_RE.test(code)) throw new Error(`invalid station code ${JSON.stringify(code)}`)
  return [
    `// Generated by the RBMC station sync (template v${RBMC_TEMPLATE_VERSION}). Manual edits are overwritten on the next sync.`,
    `const CODE = '${code}'`,
    `const rows = await ctx.ntrip.sourcetable()`,
    `const found = rows.filter((r) => r.network === 'RBMC-IP' && r.mountpoint.slice(0, 4) === CODE)`,
    'for (const r of found) ctx.log(`${r.mountpoint}: ${r.format} ${r.navSystem} via ${r.generator}`)',
    'ctx.assert(`Station ${CODE} is listed in the RBMC-IP sourcetable`, found.length > 0,',
    '  `No mountpoint starting with ${CODE} in the RBMC-IP sourcetable`)',
    `return true`,
    ``,
  ].join('\n')
}

/**
 * Matches both the hand-made names (`RBMC - VICO0 - Vicosa`) and generated ones
 * (`RBMC - VICO - Vicosa`). Group 1 = code, group 2 = mountpoint suffix ('' when
 * absent), group 3 = city label.
 */
export const STATION_TEST_NAME_RE = /^RBMC - ([A-Z0-9]{4})([0-9]?) - (.+)$/
